name: Application Serializer Test Suite
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.0']
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Run Test Suite
      run: |
        gem install bundler:1.17.3
        bundle
        bundle exec rake spec